---
title: "Mobile Device Usage App Prep"
format: html
editor: visual
---

### Load required packages

```{r}
library(tidyverse)
library(janitor)
library(ggalluvial)
library(ggmosaic)
```

### Read in data set

```{r}
user_behavior_dataset <-
  read_csv("user_behavior_dataset.csv") |>
  clean_names() |>
  mutate(across(c(device_model, operating_system, gender, user_behavior_class), as.factor)) |>
  mutate(user_id = as.character(user_id))
```

## Numerical and graphical summaries

### One-way and two-way contingency tables

```{r}
user_behavior_dataset |>
  group_by(device_model) |>
  summarise(count = n())
```

```{r}
user_behavior_dataset |>
  group_by(device_model, gender) |>
  summarise(count = n()) |>
  pivot_wider(names_from = gender, values_from = count)
```

### Numeric summaries (means, medians, sds, etc.) for quantitative variables at levels of categorical variables

```{r}
user_behavior_dataset |>
  group_by(user_behavior_class) |>
  summarise(across(where(is.numeric),
                   list("mean" = mean, "median" = median, "stdev" = sd, "IQR" = IQR),
                   .names = "{.fn}_{.col}"))|>
  mutate(across(where(is.numeric), round, 2))
```

```{r}
user_behavior_dataset |>
  group_by(gender) |>
  summarise(across(where(is.numeric),
                   list("mean" = mean, "median" = median, "stdev" = sd, "IQR" = IQR),
                   .names = "{.fn}_{.col}"))|>
  mutate(across(where(is.numeric), round, 2))
```

```{r}
user_behavior_dataset |>
  group_by(device_model) |>
  summarise(across(where(is.numeric),
                   list("mean" = mean, "median" = median, "stdev" = sd, "IQR" = IQR),
                   .names = "{.fn}_{.col}"))|>
  mutate(across(where(is.numeric), round, 2))
```

```{r}
user_behavior_dataset |>
  group_by(operating_system) |>
  summarise(across(where(is.numeric),
                   list("mean" = mean, "median" = median, "stdev" = sd, "IQR" = IQR),
                   .names = "{.fn}_{.col}"))|>
  mutate(across(where(is.numeric), round, 2))
```

```{r}
user_behavior_dataset |>
  ggplot(aes(x = user_behavior_class, fill = device_model)) +
  geom_bar(position = "fill") +
  xlab("User Behavior Class") +
  ylab("Percent") +
  scale_y_continuous(labels = scales::percent) +
  labs(fill = "Device Model") +
  ggtitle("Device Models by User Behavior Classification") +
  scale_fill_brewer(palette="Set1")
```

```{r}
user_behavior_dataset |>
  ggplot(aes(x = gender, fill = user_behavior_class)) +
  geom_bar(position = "dodge") +
  xlab("Gender") +
  ylab("Count") +
  labs(fill = "User Behavior Class") +
  ggtitle("User Behavior Classification by Gender") +
  scale_fill_brewer(palette="Set1")
```

```{r}
user_behavior_dataset |>
  ggplot(aes(number_of_apps_installed, operating_system)) +
  geom_boxplot(aes(fill = operating_system)) +
  coord_flip() +
  xlab("Number of Apps Installed") +
  ylab("Operating System") +
  labs(title = "App Installation Distribution",
       subtitle = "Considering Effects of Operating System", fill = "Operating System") +
  theme(legend.position = "none") +
  scale_fill_brewer(palette="Set1")
```

```{r}
user_behavior_dataset |>
  select(where(is.numeric)) |>
  cor() |>
  round(2)
```

```{r}
user_behavior_dataset |>
  ggplot(aes(age, screen_on_time_hours_day, color = gender)) +
  geom_point() +
  scale_color_brewer(palette = "Set1") +
  xlab("Age") +
  ylab("Screen Time") +
  labs(title = "Relationship between Age and Screen Time",
       subtitle = "Considering Effects of Gender and Device Model",
       color = "Gender") +
  facet_wrap(~ device_model)
```

```{r}
#| warning: false

user_behavior_dataset |>
  mutate(screen_time = cut(screen_on_time_hours_day,
                        breaks = 5,
                        labels = c("Low", "Med-Low", "Medium", "Med-High", "High"))) |>
  mutate(app_usage = cut(app_usage_time_min_day,
                        breaks = 5,
                        labels = c("Low", "Med-Low", "Medium", "Med-High", "High"))) |>
  mutate(data_usage = cut(data_usage_mb_day,
                        breaks = 5,
                        labels = c("Low", "Med-Low", "Medium", "Med-High", "High"))) |>
  ggplot(aes(axis1 = app_usage, axis2 = screen_time, axis3 = data_usage)) +
  geom_alluvium(aes(fill = user_behavior_class)) +
  geom_stratum() +
  geom_label(stat = "stratum", aes(label = after_stat(stratum))) +
  scale_x_discrete(limits = c("App Usage", "Screen Time", "Data Usage")) +
  labs(fill = "User Behavior Class") +
  ggtitle("Exploring Composition of User Behavior Classification") +
  scale_fill_brewer(palette="Set1")
```

```{r}
#| warning: false

user_behavior_dataset |>
  mutate(age_group = cut(age,
                        breaks = c(15, 25, 35, 45, 55, 65),
                        labels = c("Under 25", "25-34", "35-44", "45-54", "55 and Over"),
                        include.lowest = T,
                        right = F)) |>
  ggplot() +
  geom_mosaic(aes(x = product(age_group), fill = user_behavior_class)) +
  theme_mosaic() +
  theme(legend.position = "none") +
  xlab("Age Group") +
  ylab("User Behavior Class") +
  ggtitle("Relative Size of User Behavior Classification by Age Group") +
  scale_fill_brewer(palette="Set1")
```
